name: Check PR Paths and Label

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'profiles/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for file changes outside /profile directory
        id: check_changes
        run: |
          git fetch origin ${{ github.base_ref }}
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          OUTSIDE_CHANGES=false
          for FILE in $FILES; do
            if [[ $FILE != "profile/"* ]]; then
              echo "::set-output name=outside_changes::true"
              OUTSIDE_CHANGES=true
              echo "Changes detected outside the /profiles directory in file: $FILE"
              break
            fi
          done
          if [[ $OUTSIDE_CHANGES == "true" ]]; then
            echo "Invalid PR due to changes outside /profile directory."
            exit 1
          fi

      - name: Label PR as invalid
        if: steps.check_changes.outputs.outside_changes == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ['invalid']
            })


    - name: Add 'Thank you' label to PR
  uses: actions/github-script@v5
  with:
    script: |
      github.rest.issues.addLabels({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.issue.number,
        labels: ['Thank you']
      })
